Fix white space errors in from the sample env config file
Fix below error seen due to white spaces in env config file.
Change env configuration to UNIX-style format.

ERROR: In file ./.env: environment variable name 'REDIS_PORT '
may not contain whitespace

Signed-off-by: Govind Singh <govind.sk85@gmail.com>